### ISSUE TITLE
Meet error during make progress

### ISSUE THREAD

**Issue by pocketdr** [QuasarApp/CQtDeployer#706]
**Describe the bug**

`Distributions/qif.cpp:72:81: error: no matching function for call to ‘QStringList::QStringList(<brace-enclosed initializer list>)’`

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45301505/183390961-7d456acd-2baa-45dc-b0b5-f17db5251954.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04
 - arch: aarch64
 - arm-linux-gnueabihf-gcc 7
 - qt 5.9.0
 - qt-installer-framework 3.2.2 build from source 

**Additional context**
I built qif from source 3.2.2 and used "make install" to install it. But when I use "qmake -r", it told me that "QtInstallerFramework not found! use binaries from PATH"
I have tried to add "CONFIG += c++11", but nothing helps.

**Comment by EndrII** [comment]
### About build on qt5.9 
it will be fixed after merge #707 
About warning 
"QtInstallerFramework not found! Use binaries from PATH"

Just ignore this message. This message warns you about you, that you do not forget to add binarycreato to path. This message does not have checks of the PATH variable, so if you configure your build system correctly this warning not be hides

**Comment by pocketdr** [comment]
@EndrII Thank you for repairing it! After Trying it on my board, I will reply the result!
